dataset: ./dataset_aligned
device: 0

encoder: gat
decoder: gat
num_hidden: 128     
num_layers: 3
num_heads: 4
num_out_heads: 1    
residual: true         
attn_drop: 0.1          
in_drop: 0.2            
norm: layernorm          
negative_slope: 0.2     
activation: relu       
concat_hidden: false


mask_rate: 0.2
replace_rate: 0.1        
drop_edge_rate: 0.0     
alpha_l: 3         
loss_fn: sce 

optimizer: adamw     
max_epoch: 500
max_epoch_f: 100         
lr: 0.0005
weight_decay: 0.0005     
lr_f: 0.001              
weight_decay_f: 0.0005   
linear_prob: false       
scheduler: true

load_model: false
save_model: true
logging: true            
wandb: true
seeds: [111]            